version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crowdprop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crowdprop
      POSTGRES_USER: crowdprop_user
      POSTGRES_PASSWORD: crowdprop_password
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - crowdprop_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crowdprop_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crowdprop.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - crowdprop_network

volumes:
  postgres_data:

networks:
  crowdprop_network:
    driver: bridge
