export enum Deliverable {
  PROMOTIONAL_VIDEO = 'PROMOTIONAL_VIDEO',
  SCRIPT = 'SCRIPT',
  CONTENT_PLAN = 'CONTENT_PLAN',
  WEEKLY_REPORT = 'WEEKLY_REPORT',
  LIVE_SESSION = 'LIVE_SESSION',
  PRODUCT_REVIEW = 'PRODUCT_REVIEW',
  INSTAGRAM_POST = 'INSTAGRAM_POST',
  TIKTOK_VIDEO = 'TIKTOK_VIDEO',
  CUSTOM = 'CUSTOM',
}
