export const mapTransactionType = (
  type: string,
):
  | 'CAMPAIGN_PAYMENT'
  | 'PROMOTER_PAYMENT'
  | 'CONSULTANT_FEE'
  | 'COMMISSION_PAYMENT'
  | 'REFUND'
  | 'WALLET_DEPOSIT' => {
  const typeMapping: Record<
    string,
    | 'CAMPAIGN_PAYMENT'
    | 'PROMOTER_PAYMENT'
    | 'CONSULTANT_FEE'
    | 'COMMISSION_PAYMENT'
    | 'REFUND'
    | 'WALLET_DEPOSIT'
  > = {
    VIEW_EARNING: 'PROMOTER_PAYMENT',
    CONSULTANT_PAYMENT: 'CONSULTANT_FEE',
    SALESMAN_COMMISSION: 'COMMISSION_PAYMENT',
    MONTHLY_PAYOUT: 'PROMOTER_PAYMENT',
    DIRECT_PAYMENT: 'CAMPAIGN_PAYMENT',
  };

  return typeMapping[type] || 'CAMPAIGN_PAYMENT';
};
